import { art, intro, sectionHead, figure, link, arrow } from './components.mjs';

const home = `<section class="home-hero"><div class="hero-copy"><p class="eyebrow">An independent practice / A fictional portfolio</p><h1>Ways of seeing.<br>Ways of <em>making.</em></h1><div class="hero-bottom"><span class="hero-symbol" aria-hidden="true">✳</span><div><p>Exploring how we experience the world.<br>Through research, images, and interactive spaces.</p>${link('/about/', 'A little about me')}</div></div></div><figure class="hero-image">${art('field')}<figcaption><span>Fig. 01 — A shared field</span><span>Inquiry × imagination</span></figcaption></figure></section>
<section class="practice-section">${sectionHead('01', 'One practice. Two perspectives.')}<div class="perspectives"><article><p class="eyebrow">A / Professional</p><h3>Questions into<br>understanding.</h3><p>Research and teaching around interaction, immersive spaces, and the ways we learn.</p><div class="inline-links">${link('/research/', 'Research')}${link('/teaching/', 'Teaching')}</div></article><article><p class="eyebrow">B / Creative</p><h3>Observations into<br>possibilities.</h3><p>Photographic studies, virtual worlds, and experiments that start with a small curiosity.</p><div class="inline-links">${link('/creative/photography/', 'Photography')}${link('/creative/vr-game-design/', 'VR / Game Design')}</div></article></div></section>
<section class="selected-section">${sectionHead('02', 'Selected explorations', link('/creative/', 'Creative index'))}<div class="selected-grid"><a class="feature-work" href="/research/shared-spaces/">${art('space')}<div class="work-meta"><span>Research / XR interaction</span><span>01</span></div><h3>Shared spaces ${arrow}</h3><p>A fictional study of presence and attention.</p></a><a class="feature-work" href="/creative/photography/">${art('still')}<div class="work-meta"><span>Photography / Visual studies</span><span>02</span></div><h3>Ordinary geometries ${arrow}</h3><p>Looking a little longer at familiar forms.</p></a></div></section>`;

const research = `${intro('01', 'Research', 'Questions worth<br>spending time with.', 'A fictional research practice at the meeting point of human experience, interaction design, and immersive technology.')}
<section class="research-feature">${sectionHead('A', 'Example research project')}<a class="research-project" href="/research/shared-spaces/"><div>${art('space')}</div><div class="research-project-copy"><p class="eyebrow">XR interaction / Fictional project</p><h2>Shared spaces</h2><p>How might a virtual environment help people notice, orient, and attend to one another?</p><span class="text-link">Explore the project ${arrow}</span><p class="small-note">Concept study · No findings or publications claimed</p></div></a></section>
<section class="content-section">${sectionHead('B', 'Lines of inquiry')}<div class="inquiry-grid"><article><span class="index">01 / Interaction</span><h3>Attention & presence</h3><p>Noticing the subtle signals that make a shared space feel shared.</p></article><article><span class="index">02 / Immersion</span><h3>Embodied experience</h3><p>Exploring how movement and perspective shape an encounter.</p></article><article><span class="index">03 / Practice</span><h3>Design as inquiry</h3><p>Using small prototypes to make open questions tangible.</p></article></div></section>
<aside class="cross-link"><p>Ideas take shape in the studio, too.</p>${link('/creative/vr-game-design/', 'Explore VR / Game Design')}</aside>`;

const project = `<div class="breadcrumb">${link('/research/', 'Back to research')}</div><section class="project-intro"><p class="eyebrow">Research / Example project / 01</p><h1>Shared spaces</h1><p class="intro-copy">A speculative study of attention and presence in a shared virtual environment.</p><div class="project-tags"><span>XR interaction</span><span>Concept study</span><span>Fictional placeholder</span></div></section><figure class="project-visual">${art('space')}<figcaption><span>Fig. 01 — A spatial relationship, drawn as a diagram</span><span>Concept image</span></figcaption></figure>
<div class="project-body"><aside class="project-facts"><h2>At a glance</h2><dl><dt>Focus</dt><dd>Presence & shared attention</dd><dt>Approach</dt><dd>Research through design</dd><dt>Status</dt><dd>Illustrative concept only</dd></dl><p class="small-note">This fictional project demonstrates a case-study structure. No study has been conducted.</p></aside><div class="project-narrative"><section><p class="eyebrow">01 / The question</p><h2>What makes a space<br>feel shared?</h2><p>Imagine two people entering the same virtual room. They can see the room, but what helps them understand where the other person is looking? This example begins with that small question.</p></section><section><p class="eyebrow">02 / A possible approach</p><h2>Make the question tangible.</h2><p>A proposed exploration would compare a few simple spatial cues: a marker, a change in scale, and a shared point of focus. Small prototypes could help frame a later discussion.</p><ol class="method-list"><li><strong>Observe</strong><span>Map moments of attention in an imagined shared activity.</span></li><li><strong>Prototype</strong><span>Sketch alternative cues in a minimal virtual room.</span></li><li><strong>Reflect</strong><span>Describe what each option invites or obscures.</span></li></ol></section><section><p class="eyebrow">03 / An open question</p><h2>Presence without distraction.</h2><p>How much information is enough? A future study might explore when a cue supports awareness and when it becomes visual noise.</p><p class="editorial-note">Space for future process images, observations, and limitations. There are no results to report in this prototype.</p></section></div></div><aside class="cross-link"><p>Another way to explore virtual space.</p>${link('/creative/vr-game-design/', 'Visit the creative practice')}</aside>`;

const teaching = `${intro('02', 'Teaching', 'Learning through<br>making & noticing.', 'An imagined teaching practice built around curiosity, iteration, and thoughtful critique.')}
<section class="teaching-statement"><p class="eyebrow">A working philosophy</p><p class="large-copy">Make something small.<br>Ask what it reveals.<br>Make it again, differently.</p><p>These sample learning formats are fictional. They suggest how course materials and teaching ideas could live alongside a research practice.</p></section>
<section class="content-section">${sectionHead('A', 'Example learning formats', '<span class="small-note">Select a format to read more</span>')}<div class="course-list">
<details open><summary><span class="index">01</span><span><strong>Interaction as inquiry</strong><small>Studio / Foundational exploration</small></span><span class="detail-icon" aria-hidden="true"></span></summary><div class="course-content"><p>Explore how an everyday interaction shapes experience, then imagine an alternative.</p><div><h3>Example activity</h3><p>Choose a familiar object. Sketch three ways its feedback could change the way someone uses it.</p><h3>Discussion prompt</h3><p>What does your design ask someone to notice?</p></div></div></details>
<details><summary><span class="index">02</span><span><strong>Thinking in virtual space</strong><small>Workshop / Immersive design</small></span><span class="detail-icon" aria-hidden="true"></span></summary><div class="course-content"><p>Use simple spatial compositions to explore scale, orientation, and movement.</p><div><h3>Example activity</h3><p>Design a room with one landmark and two possible routes. Describe how each route changes the experience.</p><h3>Discussion prompt</h3><p>How can a space guide someone without instructions?</p></div></div></details>
<details><summary><span class="index">03</span><span><strong>Looking as a practice</strong><small>Seminar / Observation & critique</small></span><span class="detail-icon" aria-hidden="true"></span></summary><div class="course-content"><p>Use a sequence of images to slow down observation and examine a familiar place.</p><div><h3>Example activity</h3><p>Frame the same subject in three ways. Discuss what enters or leaves the story with each crop.</p><h3>Discussion prompt</h3><p>What changed in the image, and what changed in your attention?</p></div></div></details></div></section><aside class="cross-link"><p>Observation is also a creative method.</p>${link('/creative/photography/', 'See the visual studies')}</aside>`;

function creativeNav(active) { return `<nav class="subnav" aria-label="Creative work"><a href="/creative/" ${active === 'all' ? 'aria-current="page"' : ''}>All creative work</a><a href="/creative/photography/" ${active === 'photo' ? 'aria-current="page"' : ''}>Photography</a><a href="/creative/vr-game-design/" ${active === 'vr' ? 'aria-current="page"' : ''}>VR / Game Design</a></nav>`; }

const creative = `${creativeNav('all')}${intro('03', 'Creative work', 'Room to<br><em>wonder.</em>', 'Images, imagined worlds, and small experiments. A space to follow a question without knowing where it will lead.')}
<section class="creative-index" aria-label="Creative disciplines"><a class="creative-entry" href="/creative/photography/">${art('still')}<div><p class="eyebrow">01 / The observed world</p><h2>Photography ${arrow}</h2><p>Light, form, and the extraordinary ordinary.</p><span class="text-link">View visual studies ${arrow}</span></div></a><a class="creative-entry" href="/creative/vr-game-design/">${art('orbit')}<div><p class="eyebrow">02 / The imagined world</p><h2>VR / Game Design ${arrow}</h2><p>Playable spaces and experiments in perception.</p><span class="text-link">Explore virtual worlds ${arrow}</span></div></a></section><section class="experiment-note"><p class="eyebrow">From the notebook / Experimental projects</p><h2>Not everything needs<br>to become something.</h2><p>A future home for unfinished sketches, material tests, and curious detours. For now, an open page.</p></section>`;

const photography = `${creativeNav('photo')}<section class="photo-intro"><div><p class="eyebrow">03.1 / Photography</p><h1>Ordinary<br><em>geometries.</em></h1></div><div><p>Studies in light, proportion, and the spaces between things.</p><p class="small-note">An imagined series. All six images are geometric placeholders, not photographs.</p></div></section>
<section class="photo-gallery" aria-label="Ordinary geometries — six placeholder compositions">${figure('still', '01 / A quiet corner', 'Form study', 'photo-wide')}${figure('aperture', '02 / In between', 'Light study', 'photo-portrait')}${figure('horizon', '03 / Almost a horizon', 'Space study', 'photo-offset')}${figure('aperture', '04 / A second look', 'Frame study', 'photo-wide alternate-crop')}${figure('still', '05 / A familiar shape', 'Form study', 'photo-offset alternate-crop')}${figure('horizon', '06 / Somewhere, slowly', 'Space study', 'photo-portrait')}</section><div class="series-end"><span class="index">End of series / 06 studies</span>${link('/creative/', 'Back to creative work')}</div>`;

const vr = `${creativeNav('vr')}${intro('03.2', 'VR / Game Design', 'Worlds to<br>find your way in.', 'Speculative environments and playful systems. Experiments in how a space can invite attention, movement, and discovery.')}
<section class="world-project"><figure>${art('orbit')}<figcaption><span>01 / A field of possibilities</span><span>Geometric concept image</span></figcaption></figure><div class="world-copy"><p class="eyebrow">Fictional concept / Spatial exploration</p><h2>A place<br>between places</h2><p>An imagined environment with no destination. A few objects, a shifting sense of scale, and space to wander.</p><dl class="compact-facts"><div><dt>Medium</dt><dd>VR environment concept</dd></div><div><dt>Interest</dt><dd>Scale, orientation, discovery</dd></div><div><dt>Status</dt><dd>Placeholder · Not playable</dd></div></dl></div></section>
<section class="content-section">${sectionHead('A', 'Design notes')}<div class="inquiry-grid"><article><span class="index">01 / Invitation</span><h3>Leave a little unsaid.</h3><p>A single object might suggest a path without prescribing one.</p></article><article><span class="index">02 / Movement</span><h3>Let the body lead.</h3><p>Distance and scale could become part of the interaction.</p></article><article><span class="index">03 / Play</span><h3>Make room for surprise.</h3><p>A simple rule might create an unexpected encounter.</p></article></div></section><aside class="cross-link"><p>The same curiosity, through a research lens.</p>${link('/research/shared-spaces/', 'Read Shared spaces')}</aside>`;

const about = `${intro('04', 'About', 'A practice<br>across boundaries.', 'Researcher, educator, and maker — a fictional profile for a portfolio in progress.')}
<div class="about-layout"><figure>${art('field')}<figcaption><span>A placeholder for a future portrait</span><span>Fig. 02</span></figcaption></figure><div class="about-copy"><p class="eyebrow">Hello / Your Name</p><h2>Curiosity is<br>the common thread.</h2><p>This placeholder profile imagines a practice moving between research, teaching, and creative work. The interests overlap: how we notice things, how we learn, and how we experience spaces.</p><p>Some questions ask for a structured investigation. Others begin with an image or a small experiment. This portfolio makes room for both.</p><p class="editorial-note">Replace this fictional biography with your own background and voice. No credentials, affiliations, or professional history are implied.</p><div class="about-interests"><h3>Areas of interest</h3><ul><li>Human–computer interaction</li><li>Immersive environments</li><li>Learning through making</li><li>Photography & observation</li></ul></div></div></div><aside class="cross-link"><p>A starting point, from either perspective.</p><div class="inline-links">${link('/research/', 'Research')}${link('/creative/', 'Creative work')}</div></aside>`;

export const pages = [
  { path: '/', title: 'Home', content: home },
  { path: '/research/', title: 'Research', content: research },
  { path: '/research/shared-spaces/', title: 'Shared spaces', content: project },
  { path: '/teaching/', title: 'Teaching', content: teaching },
  { path: '/creative/', title: 'Creative Work', content: creative },
  { path: '/creative/photography/', title: 'Photography', content: photography },
  { path: '/creative/vr-game-design/', title: 'VR / Game Design', content: vr },
  { path: '/about/', title: 'About', content: about },
];
